import {copyFile, mkdir, readFile, readdir, rm, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const docsSiteRoot = path.resolve(scriptDir, '..');
const repoRoot = path.resolve(docsSiteRoot, '..');

const pages = [
  {
    source: path.join(repoRoot, 'non-containerized', 'README.md'),
    target: path.join(docsSiteRoot, 'docs', 'download-and-installation', 'non-containerized.md'),
  },
  {
    source: path.join(repoRoot, 'docker', 'README.md'),
    target: path.join(docsSiteRoot, 'docs', 'download-and-installation', 'docker-based.md'),
  },
  {
    source: path.join(repoRoot, 'utils', 'csv', 'README.md'),
    target: path.join(docsSiteRoot, 'docs', 'technical-details', 'pre-processing-script.md'),
    transform: (markdown) =>
      markdown.replace(
        '## ⏱️ Duration binning (days → ISO8601 PnU)',
        '## Duration binning days to ISO8601 PnU',
      ),
  },
];

function asGeneratedPage(markdown, sourcePath) {
  const relativeSource = path.relative(repoRoot, sourcePath);

  return [
    '<!--',
    `Generated from ${relativeSource}.`,
    'Do not edit this file directly; edit the source README and run npm run sync:readmes from docs-site.',
    '-->',
    '',
    markdown.trimEnd(),
    '',
  ].join('\n');
}

await Promise.all(
  pages.map(async ({source, target, transform}) => {
    const markdown = await readFile(source, 'utf8');
    await mkdir(path.dirname(target), {recursive: true});
    await writeFile(target, asGeneratedPage(transform ? transform(markdown) : markdown, source), 'utf8');
  }),
);

const schemaSourceRoot = path.join(repoRoot, 'share', 'versions');
const schemaTargetRoot = path.join(docsSiteRoot, 'static', 'schemas');
const schemaName = 'clarid-codebook-schema.json';
const versionDirectories = (await readdir(schemaSourceRoot, {withFileTypes: true}))
  .filter((entry) => entry.isDirectory() && /^\d+\.\d+$/.test(entry.name))
  .map((entry) => entry.name)
  .sort((left, right) => left.localeCompare(right, undefined, {numeric: true}));

await rm(schemaTargetRoot, {recursive: true, force: true});
await Promise.all(
  versionDirectories.map(async (version) => {
    const source = path.join(schemaSourceRoot, version, schemaName);
    const target = path.join(schemaTargetRoot, version, schemaName);
    await mkdir(path.dirname(target), {recursive: true});
    await copyFile(source, target);
  }),
);

console.log(
  `Synced ${pages.length} README-backed pages and ${versionDirectories.length} versioned schemas.`,
);
